"""工具模块 - 统一的搜索工具"""

from .search_tools import (
    baidu_search,
    baidu_news_search,
    bing_search,
    bing_news_search,
    sogou_search,
    sogou_news_search,
    google_search,
    google_news_search,
    search_360,
    search_360_news,
    toutiao_search,
    toutiao_news_search,
    tencent_search,
    tencent_news_search,
    wangyi_search,
    wangyi_news_search,
    sina_search,
    sina_news_search,
    sohu_search,
    sohu_news_search,
    multi_search,
    fetch_article_content,
    baidu_hot_search,
)

__all__ = [
    "baidu_search",
    "baidu_news_search",
    "bing_search",
    "bing_news_search",
    "sogou_search",
    "sogou_news_search",
    "google_search",
    "google_news_search",
    "search_360",
    "search_360_news",
    "toutiao_search",
    "toutiao_news_search",
    "tencent_search",
    "tencent_news_search",
    "wangyi_search",
    "wangyi_news_search",
    "sina_search",
    "sina_news_search",
    "sohu_search",
    "sohu_news_search",
    "multi_search",
    "fetch_article_content",
    "baidu_hot_search",
]
